language: go
sudo: false
go:
- 1.10.x
install: go get -u -t -v ./...
before_deploy: make
deploy:
  provider: releases
  prerelease: true
  skip_cleanup: true
  file_glob: true
  file: bin/*
  # draft: true
  overwrite: true
  on:
    repo: rc452860/vnet
    branch: master
    tags: true
  api_key: 
    secure: cdCjHQaPWHJoKIBZ0qXN47kn/LpEIkgLshVTi+xckQl/gDpJ0U/rSh8BMSl4Do3fYRuIPnmlQygDYc4nhYmMLEJA2tGwLmmVw7AYJI8o8+xXLKDcL2J2JVHER3h4m0fFWDkZlaxPGX3UgBFKabWhxwwuTqQdjLK7SaU6r1xmKuaU1z2Ufq/m5nV86DYbsPccMjBAN2UKl3kA0hdwVPDuBUr33ZqoXa+z/9PiVeJQM8WHF9SNqy/5YHp4VTfnZti41hH+7dyqkpu5uM1L/kVzfVLLJZ7f2bBQeOrIh/l4zfnT63rq5wJO9pgj/ETegPGw8xjI7M3dO0cBELRHN50sZgBTc0/Rl7/St5oHe20u2t6m/DKvyPj0T5ghvnE2PNcQwvo/jWQ8Qq9b94VK32T57+r+TS85A3iQ5fZUrz46tqhi7W959I8cwsQMz2yzwGl/qjkczfIvFRAjW/kmnbBRzdpItL1SVdFuhNHg1ysvDsAa4EHqw+nK+THdKZOrHuNUgSWHaCxDdn9mE3pRb7xg+M+brpmlEX0OF8/5oJ6ix5D7NGk3gEK1fm4tbc8fPnk8Nz95rhhy6bxaYnvCmKJcDU+KXy1M5SHmtEG72BH4YrUNHLqJpyFOCm6gwFhxsXcT9JCEZIhPQCKW8ODnYNVcyA62rrjOVs9UZWoYxam4SBk=
